version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /deploy/cloudformation/functions
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /packages/control-plane
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /crates/egress-gateway
    schedule: { interval: weekly }
